[package]
name = "crypto-api"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenvy_macro = "0.15.7"
reqwest = { version = "0.12.2", features = ["json"] }
tokio = { version = "1.37.0", features = ["macros", "rt", "rt-multi-thread"] }
